use master 
go
create database QLTracNghiem
go
use QLTracNghiem 
go
create table MonHoc
(
	MAMH CHAR(10) NOT NULL,
	TENMH NVARCHAR(50) NOT NULL UNIQUE,
	GHICHU NVARCHAR(50),
	CONSTRAINT PK_MH PRIMARY KEY(MAMH)
)
CREATE TABLE CHUONG
(
	MACHUONG CHAR(10) NOT NULL,
	TENCHUONG NVARCHAR(50) NOT NULL UNIQUE,
	MAMH CHAR(10),
	CONSTRAINT PK_CHUONG PRIMARY KEY(MACHUONG),
	CONSTRAINT FK_CHUONG_MH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)
)
CREATE TABLE CAUHOI
(
	MACAUHOI CHAR(10) NOT NULL,
	NOIDUNGCAUHOI NVARCHAR(200)  NOT NULL,
	PAN_A NVARCHAR(200) NOT NULL,
	PAN_B NVARCHAR(200) NOT NULL,
	PAN_C NVARCHAR(200) NOT NULL,
	PAN_D NVARCHAR(200) NOT NULL,
	CAU_TRALOI NVARCHAR(200),
	MACHUONG CHAR(10),
	CONSTRAINT PK_CAUHOI PRIMARY KEY(MACAUHOI),
	CONSTRAINT FK_CAUHOI_CHUONG FOREIGN KEY(MACHUONG) REFERENCES CHUONG(MACHUONG)
)
CREATE TABLE HOCVIEN(
	MAHV CHAR(13) NOT NULL,
	HOLOT NVARCHAR(50) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	PHAI NCHAR(3) NOT NULL,
	SODT CHAR(10),
	CONSTRAINT PK_HV PRIMARY KEY(MAHV)
)
CREATE TABLE DETHI(
	MADETHI CHAR(10) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	CONSTRAINT PK_DETHI PRIMARY KEY(MADETHI),
	CONSTRAINT FK_DETHI_MH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)
)
CREATE TABLE CHITIET_DETHI(
	MADETHI CHAR(10),
	MACAUHOI CHAR(10),
	CONSTRAINT PK_CTDT PRIMARY KEY(MADETHI, MACAUHOI),
	CONSTRAINT FK_CTDT_DT FOREIGN KEY(MADETHI) REFERENCES DETHI(MADETHI),
	CONSTRAINT FK_CTDT_CH FOREIGN KEY(MACAUHOI) REFERENCES CAUHOI(MACAUHOI)
)
CREATE TABLE KETQUA(
	IDKETQUA CHAR(10),
	MADETHI CHAR(10),
	MAHV CHAR(13),
	TONGSODIEM FLOAT,
	CONSTRAINT PK_KQ PRIMARY KEY(IDKETQUA),
	CONSTRAINT FK_KQ_HV FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV),
	CONSTRAINT FK_KQ_DT FOREIGN KEY(MADETHI) REFERENCES DETHI(MADETHI)
)
CREATE TABLE CT_KETQUA
(
	IDKETQUA CHAR(10),
	MACAUHOI CHAR(10),
	CAUTRALOI NVARCHAR(200),
	CONSTRAINT PK_CT_KQ PRIMARY KEY(IDKETQUA, MACAUHOI),
	CONSTRAINT FK_CT_KQ_CH FOREIGN KEY(MACAUHOI) REFERENCES CAUHOI(MACAUHOI),
	CONSTRAINT FK_CT_KQ_KQ FOREIGN KEY(IDKETQUA) REFERENCES KETQUA(IDKETQUA)
)
CREATE TABLE LOPHOC
(
	MALOP CHAR(10) NOT NULL,
	TENLOP NVARCHAR(50) NOT NULL UNIQUE,
	GIAOVIEN NVARCHAR(30)
	CONSTRAINT PK_LH PRIMARY KEY(MALOP)
)
CREATE TABLE LOP_MONHOC
(
	MALOP CHAR(10),
	MAMH CHAR(10),
	CONSTRAINT PK_LOP_MH PRIMARY KEY(MALOP, MAMH),
	CONSTRAINT FK_LOP_MH_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT FK_LOP_MH_LOP FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)
)
ALTER TABLE HOCVIEN
ADD MALOP CHAR(10)

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HV_LOP FOREIGN KEY(MALOP) REFERENCES LOPHOC(MALOP)